name: musicapp
description: "A new Flutter project."
publish_to: 'none'

version: 3.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  provider: ^6.0.5
  http: ^1.2.0
  package_info_plus: ^8.0.0
  url_launcher: ^6.2.5
  just_audio: ^0.9.38

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
